### ISSUE TITLE
Kind of a joke.

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/js-basics-intro-to-javascript-readme#16]
"And, finally, it's a great first or second language to learn."

Y U NO TEACH SOONER?

**Comment by sgharms** [comment]
I'm not sure how best to reply here, but there are many good reasons to put a back-end language with strong OO opinions first. As you continue your study here, you'll surely encounter surprises with the language. With a model of programming (say, Ruby), you might find it possible to theorize and address "surprises" because you have a prior model of computation. In time, I hope you will see for yourself why we move the Ruby Zig for Great Justice.

![image](https://user-images.githubusercontent.com/50019/52210855-2c79f780-2856-11e9-84d8-285255a84705.png)


For further [consideration](https://stevengharms.com/posts/2015-04-01-teaching-ruby-over-javascript/)

Memefully yours,

Steven
